"""Image-aware diagnostics and preregistered sampling; no chemistry certificate."""

from itertools import permutations
import json
from pathlib import Path, PureWindowsPath

import numpy as np


BOND_CUTOFFS = {('C', 'C'): 1.75, ('C', 'H'): 1.3, ('C', 'O'): 1.65,
                ('C', 'N'): 1.75, ('N', 'H'): 1.3, ('O', 'H'): 1.3, ('Zr', 'O'): 2.8}


def frozen_input_path(root, relative):
    """Resolve frozen Windows/POSIX relative paths inside the runtime bundle."""
    parts = PureWindowsPath(relative)
    if parts.drive or parts.root:
        raise ValueError('Frozen input must be a relative bundle path')
    root = Path(root).resolve()
    result = root.joinpath(*parts.parts).resolve()
    if not result.is_relative_to(root):
        raise ValueError('Frozen input escapes the bundle root')
    return result


def refinement_jobs(plan, reports):
    """Select registered target/random winners for four registered designs."""
    pools = {}
    for path in reports:
        run = json.loads(path.read_text())
        if run['plan_sha256'] != plan['_sha256'] or run['protocol'] != plan['protocol']:
            raise ValueError('Refinement reports do not match frozen plan')
        for row in run['results']:
            if row['id'] in pools or row['status'] != 'complete_model_sample':
                raise ValueError('Duplicate or incomplete pilot input')
            pools[row['id']] = (path, run, row)
    if set(pools) != {r['id'] for r in plan['configurations']}:
        raise ValueError('Audit the full eight-configuration pilot before refinement')
    jobs = []
    for key in plan['force_check']['ids']:
        path, run, row = pools[key]
        winners = []
        for gas in ('CO2','H2O'):
            for category in ('targeted','random_void'):
                eligible = [s for s in row['starts'] if s['gas']==gas and
                    ((s['placement']['site_class']=='random_void') == (category=='random_void'))]
                winners.append(min(eligible, key=lambda s:(s['system']['final_energy_ev'],s['start'])))
        jobs.append((path, run, row, winners))
    return jobs


def periodic_edges(atoms):
    """Undirected (i,j,Sx,Sy,Sz) edges, including multiple/self images."""
    from ase.neighborlist import neighbor_list
    left, right, shifts = neighbor_list('ijS', atoms, BOND_CUTOFFS)
    return {min((int(i), int(j), *map(int, s)), (int(j), int(i), *map(int, -s)))
            for i, j, s in zip(left, right, shifts)}


def periodic_change(initial, final):
    """Compare image edges after placing final atoms in the initial atom gauge."""
    from ase.geometry import find_mic
    if not np.array_equal(initial.numbers, final.numbers) or not np.allclose(
            initial.cell.array, final.cell.array, atol=1e-7, rtol=0):
        raise ValueError('Same atom order/cell required for periodic audit')
    aligned = final.copy()
    displacement, _ = find_mic(final.positions-initial.positions, initial.cell, initial.pbc)
    aligned.positions = initial.positions + displacement
    before, after = periodic_edges(initial), periodic_edges(aligned)
    return {'lost_image_edges': [list(e) for e in sorted(before-after)],
            'gained_image_edges': [list(e) for e in sorted(after-before)]}


def network_winding_rank(atoms):
    """Rank of image translations generated by cycles in the inferred bond graph."""
    edges = periodic_edges(atoms)
    adjacency = {i: [] for i in range(len(atoms))}
    for i, j, *shift in edges:
        s = np.array(shift, dtype=int)
        adjacency[i].append((j, s))
        adjacency[j].append((i, -s))
    images, cycles, components = {}, [], 0
    for seed in range(len(atoms)):
        if seed in images:
            continue
        components += 1
        images[seed], pending = np.zeros(3, dtype=int), [seed]
        while pending:
            i = pending.pop()
            for j, shift in adjacency[i]:
                trial = images[i] + shift
                if j in images:
                    cycles.append(trial-images[j])
                else:
                    images[j] = trial
                    pending.append(j)
    return {'components': components, 'winding_rank': int(np.linalg.matrix_rank(cycles))
            if cycles else 0, 'image_edges': len(edges)}


def linker_node_graph(parent, mapping):
    """Unwrap the finite Zr6 node and map six linker bridges to node images."""
    from ase.neighborlist import neighbor_list
    node = set(mapping['node_atom_indices'])
    ii, jj, shifts = neighbor_list('ijS',parent,BOND_CUTOFFS)
    adjacency = {i:[] for i in node}
    for i,j,s in zip(ii,jj,shifts):
        if i in node and j in node:
            adjacency[int(i)].append((int(j),s))
    seed = min(node)
    images, pending = {seed:np.zeros(3,dtype=int)},[seed]
    while pending:
        i = pending.pop()
        for j,s in adjacency[i]:
            trial = images[i]+s
            if j in images and not np.array_equal(trial,images[j]):
                raise ValueError('Zr6 node winds periodically; finite node mapping failed')
            if j not in images:
                images[j] = trial
                pending.append(j)
    if set(images)!=node:
        raise ValueError('Node component disconnected')
    bridges, neighbors = [],set()
    for slot in mapping['slots']:
        ids = slot['atom_indices']
        carbons = [i for i in ids if parent.numbers[i]==6]
        co_counts = {c:int(np.sum((ii==c)&(parent.numbers[jj]==8))) for c in carbons}
        carboxyls = [c for c,n in co_counts.items() if n==2]
        ring = [c for c in carbons if co_counts[c]==0]
        if len(carboxyls)!=2 or len(ring)!=6 or any(np.sum((ii==c)&np.isin(jj,ring))!=2 for c in ring):
            raise ValueError('BDC ring/carboxyl topology failed')
        ends = []
        for o in ids:
            if parent.numbers[o]!=8:
                continue
            bonds = [(int(j),s) for j,s in zip(jj[ii==o],shifts[ii==o]) if parent.numbers[j]==40]
            if len(bonds)!=1:
                raise ValueError('Each carboxyl O must bind one Zr image')
            j,s = bonds[0]
            ends.append(tuple(np.array(slot['image_shifts'][str(o)])+s-images[j]))
        unique = sorted(set(ends))
        if len(unique)!=2 or any(ends.count(e)!=2 for e in unique):
            raise ValueError('Linker must bridge two node images through two O each')
        shift = tuple(np.array(unique[1])-unique[0])
        if shift==(0,0,0):
            raise ValueError('Linker does not bridge nodes')
        neighbors.update((shift,tuple(-np.array(shift))))
        bridges.append({'slot':slot['id'],'node_images':[list(map(int,e)) for e in unique],
                        'bridge_translation':list(map(int,shift)),'node_separation_angstrom':float(np.linalg.norm(np.array(shift)@parent.cell.array))})
    if len(neighbors)!=12:
        raise ValueError('Six linkers do not provide twelve distinct node neighbors')
    return {'node_count_per_cell':1,'node_degree':12,'linker_bridges':bridges,
            'neighbor_translations':[list(map(int,n)) for n in sorted(neighbors)],
            'scope':'distance-inferred 12-connected net; template/synthesis certification requires expert'}


def _unit(vector):
    norm = np.linalg.norm(vector)
    if norm < 1e-10:
        raise ValueError('Degenerate site direction')
    return vector/norm


def site_anchors(host, mapping):
    """Four operational site classes; chemical interpretation requires review."""
    from ase.geometry import find_mic
    from ase.neighborlist import neighbor_list
    slots = mapping['slots']
    i, j = neighbor_list('ij', host, {('O', 'H'): 1.3})
    node = mapping['node_atom_indices']
    hydroxyls = [(o, h) for o, h in zip(i, j) if o in node and h in node
                 and host.numbers[o] == 8 and host.numbers[h] == 1]
    if len(hydroxyls) != 4:
        raise ValueError('Four node OH groups required; do not guess missing H')
    anchors = {'node_OH': [], 'node_oxo': [], 'linker_face': [], 'substitution_pocket': []}
    for o, h in sorted(hydroxyls):
        direction, _ = find_mic(host.positions[h]-host.positions[o], host.cell, True)
        anchors['node_OH'].append((f'O{o}-H{h}', host.positions[o], _unit(direction)))
    for o in node:
        if host.numbers[o] == 8 and o not in [a for a, _ in hydroxyls]:
            anchors['node_oxo'].append((f'O{o}', host.positions[o], None))
    for slot in slots:
        c, h = slot['substitution_carbon'], slot['substitution_hydrogen']
        ids = [c, *slot['ring_neighbors']]
        vectors, _ = find_mic(host.positions[ids]-host.positions[c], host.cell, True)
        normal = _unit(np.cross(vectors[1], vectors[2]))
        # Ring carbons have two or three C neighbors; carboxyl C has one.
        carbon = [k for k in slot['atom_indices'] if host.numbers[k] == 6]
        ii, jj = neighbor_list('ij', host, {('C', 'C'): 1.75})
        ring = [k for k in carbon if np.sum(ii == k) >= 2]
        if len(ring) != 6:
            raise ValueError('Six ring carbons required')
        v, _ = find_mic(host.positions[ring]-host.positions[c], host.cell, True)
        anchors['linker_face'].append((slot['id'], host.positions[c]+v.mean(axis=0), normal))
        v, _ = find_mic(host.positions[h]-host.positions[c], host.cell, True)
        kind = 'NH2' if host.numbers[h] == 7 else 'CH_control'
        anchors['substitution_pocket'].append((slot['id']+'_'+kind, host.positions[h], _unit(v)))
    return anchors


def pilot_proposals(host, gas, mapping, config_index, gas_index, master_seed=20261003):
    """32 independent seed streams: two batches of 8 targeted + 8 random starts.

    Each targeted class receives two starts per batch. Initial gas coordinates
    [3,3] and labels are frozen before energies; no replacement of failed runs.
    """
    from ase.geometry import find_mic
    from scipy.spatial.transform import Rotation
    anchors = site_anchors(host, mapping)
    classes = list(anchors)
    centered = gas.positions-gas.get_center_of_mass()
    poses = []
    for batch in range(2):
        for slot in range(16):
            seed = [master_seed, config_index, gas_index, batch, slot]
            rng = np.random.default_rng(np.random.SeedSequence(seed))
            category = classes[slot//2] if slot < 8 else 'random_void'
            options = anchors.get(category)
            anchor = options[int(rng.integers(len(options)))] if options else None
            for proposal in range(2000):
                rotation = Rotation.random(random_state=rng).as_matrix()
                if anchor:
                    name, origin, axis = anchor
                    direction = _unit(rng.normal(size=3) if axis is None else
                                      ((-axis if category == 'linker_face' and slot%2 else axis)
                                       + .35*rng.normal(size=3)))
                    center = origin+rng.uniform(3.0, 4.5)*direction
                else:
                    name, center = 'uniform_fractional', rng.random(3) @ host.cell.array
                xyz = centered @ rotation.T + center
                _, distance = find_mic((host.positions[:, None]-xyz[None]).reshape(-1, 3), host.cell, True)
                if distance.min() < 2.0:
                    continue
                # Random streams are independent; exact repeated accepted poses rejected.
                if any(np.max(np.abs(xyz-np.array(p['guest_positions_angstrom']))) < 1e-8 for p in poses):
                    continue
                poses.append({'start': batch*16+slot, 'batch': batch, 'batch_slot': slot,
                    'site_class': category, 'site_anchor': name, 'seed_entropy': seed,
                    'proposal': proposal, 'guest_positions_angstrom': xyz.tolist(),
                    'rotation': rotation.tolist(), 'fractional_center': (center @ np.linalg.inv(host.cell.array)).tolist(),
                    'minimum_host_guest_distance_angstrom': float(distance.min())})
                break
            else:
                raise ValueError(f'Placement exhausted for {category}; no random fallback')
    return poses


def pose_distance(left, right, host_count):
    """Framework-anchored periodic RMSD; equivalent guest atoms may permute."""
    from ase.geometry import find_mic
    if not np.array_equal(left.numbers, right.numbers) or not np.allclose(left.cell, right.cell):
        raise ValueError('Same ordered system required for pose matching')
    shift, _ = find_mic(right.positions[:host_count]-left.positions[:host_count], left.cell, True)
    translation = shift.mean(axis=0)
    host_rmsd = float(np.sqrt(np.mean(np.sum((shift-translation)**2, axis=1))))
    guest = left.numbers[host_count:]
    best = float('inf')
    for order in permutations(range(len(guest))):
        if not np.array_equal(guest, guest[list(order)]):
            continue
        delta = right.positions[host_count+np.array(order)]-left.positions[host_count:]-translation
        v, _ = find_mic(delta, left.cell, True)
        best = min(best, float(np.sqrt(np.mean(np.sum(v*v, axis=1)))))
    return host_rmsd, best


def cluster_minima(items, host_count, energy_tolerance=.01, host_tolerance=.15, guest_tolerance=.35):
    """Deterministic complete-link approximate basins; not symmetry certification.

    items: list of (start_id, total_energy_eV, ASE Atoms). Retain all members.
    """
    groups = []
    for item in sorted(items, key=lambda r: (r[1], r[0])):
        for group in groups:
            if all(abs(item[1]-other[1]) <= energy_tolerance and
                   all(d <= t for d, t in zip(pose_distance(item[2], other[2], host_count),
                                              (host_tolerance, guest_tolerance))) for other in group):
                group.append(item)
                break
        else:
            groups.append([item])
    return [{'start_ids': [r[0] for r in group], 'minimum_system_energy_ev': min(r[1] for r in group)}
            for group in groups]
